config/routes.rb
Icoddle::Application.routes.draw do
  # landing page related
  root :to => 'leads#new', :as => :homepage
  match '/landing' => 'leads#new'

  # login/register/signup related
  match '/signup/:invitation_token' => 'users#new', :as => :signup
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  # artifacts of cruft
  get "home/index"
  match '/home' => 'home#index'
  match '/users' => 'users#index'

  # actual default REST route management
  # try rake routes to checkout all the helpers created for routes

  # stand alone routing
  resources :leads
  resources :user_sessions

  # nested routing
  resources :users
  resources :pets

  # not stand-alone but not sure if nesting helps 
  resources :invitations
  resources :friendships
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  has_attached_file :photo,
    :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :storage => :s3,
    :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET']
    },
    :bucket => ENV['S3_BUCKET'], 
    :path => "/:style/:id/:filename"
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # GET /pets
  # GET /pets.json
  def index
    @pets = current_user.pets

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pets }
    end
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @pet = Pet.find(params[:id])

    respond_to do |format|
      if (current_user.id == @pet.user_id)
        format.html # show.html.erb
        format.json { render json: @pet }
      else
        flash[:error] = "You are only authorised to view your own pets' profiles. Please login as the owner to view this pet."
        redirect_to pets_url
      end
    end
  end

  # GET /pets/new
  # GET /pets/new.json
  def new
    @pet = Pet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pet }
    end
  end

  # GET /pets/1/edit
  def edit
    @pet = Pet.find(params[:id])

    if (current_user.id != @pet.user_id)
      flash[:error] = "You are only authorised to edit your own pets' profiles. Please login as the owner to edit this pet."
      redirect_to pets_url
    end
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(params[:pet])

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet profile was successfully created.' }
        format.json { render json: @pet, status: :created, location: @pet }
      else
        format.html { render action: "new" }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pets/1
  # PUT /pets/1.json
  def update
    @pet = Pet.find(params[:id])
    # @pet_x = current_user.pets.where(:id => params[:id])

    respond_to do |format|
      if @pet.update_attributes(params[:pet])
        format.html { redirect_to @pet, notice: 'Pet profile was successfully saved.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :ok }
    end
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.haml
= form_for @pet do |f|
  -if @pet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pet.errors.count, "error")} prohibited this pet from being saved:"
      %ul
        - @pet.errors.full_messages.each do |msg|
          %li= msg

  .row
    .column.grid_6
      .field
        = f.label :name
        = f.text_field :name
      .field
        = f.label :photo
        = f.file_field :photo
      .field
        = f.label :age
        = f.text_field :age
      .field
        = f.label :dob
        = f.date_select :dob

      .field
        = f.hidden_field :user_id, :value => current_user.id

    .column.grid_6
      .field
        = f.label :notes
        = f.text_area :notes
      .actions
        = f.submit 'Save'

app/views/pets/edit.html.haml
%h1 Edit Your Pet's Profile

= render 'form'

app/views/pets/index.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag 'pets'

%h1 Your Pets

- @pets.each do |pet|
  .pet-profile
    = link_to pet.name, pet  

.pet-create
  = link_to 'Create Pet ...', new_pet_path

-# %td= link_to 'Show', pet
-# %td= link_to 'Edit', edit_pet_path(pet)
-# %td= link_to 'Destroy', pet, :confirm => 'Are you sure?', :method => :delete

app/views/pets/new.html.haml
%h1 Create a Profile for Your Pet

= render 'form'

app/views/pets/show.html.haml
%h1 Your Pet's Profile

.row
  .column.grid_6
    %p.pet-profile-element
      %b Name:
      = @pet.name
    %p.pet-profile-element
      = link_to image_tag @pet.photo.url(:thumb)
    %p.pet-profile-element
      %b Age:
      = @pet.age
    %p.pet-profile-element
      %b Dob:
      = @pet.dob
  .column.grid_6
    %p.pet-profile-element
      %b Notes:
      = @pet.notes
.row
  .column.grid_6
    &nbsp;
  .column.grid_6
    = link_to 'Edit', edit_pet_path(@pet)
    \|
    = link_to 'Delete', @pet, :confirm => 'Are you sure?', :method => :delete