config/routes.rb
Icoddle::Application.routes.draw do
  # landing page related
  root :to => 'leads#new', :as => :homepage
  match '/landing' => 'leads#new'

  # login/register/signup related
  match '/signup/:invitation_token' => 'users#new', :as => :signup
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  # artifacts of cruft
  get "home/index"
  match '/home' => 'home#index'
  match '/users' => 'users#index'

  # actual default REST route management
  # try rake routes to checkout all the helpers created for routes

  # stand alone routing
  resources :leads
  resources :user_sessions

  # nested routing
  resources :users
  resources :pets

  # not stand-alone but not sure if nesting helps 
  resources :invitations
  resources :friendships
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic 
  has_many :pets, :dependent => :destroy
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  #validates_presence_of :username, :message => 'cannot be empty'
  #validates_presence_of :invitation_id, :message => 'is required'
  validates_uniqueness_of :invitation_id

  has_many :sent_invitations, :class_name => 'Invitation', :foreign_key => 'sender_id'
  belongs_to :invitation

  before_create :set_invitation_limit
  after_create :set_invitation_status

  attr_accessible :username, :login, :email, :name, :password, :password_confirmation, :invitation_token

  def invitation_token
    invitation.token if invitation
  end

  def invitation_token=(token)
    self.invitation = Invitation.find_by_token(token)
  end

  private

  def set_invitation_limit
    self.invitation_limit = 25
  end

  def set_invitation_status
    invites = Invitation.where(:recipient_email => self.email)
    invites.each do |invite|
      invite.status = 1
      invite.save
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_login, :only => [:new, :create]

  # GET /users
  # GET /users.json
  def index
    # Eventually we will not need access to @users
    @friendships = current_user.friendships
    @friends = current_user.friendships.collect(&:friend).collect(&:username)
    @invitations_sent = current_user.sent_invitations
    @invitations_recv = Invitation.where(:recipient_email => current_user.email)
    @other_users = User.all.delete(current_user)
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    puts 'params'
    puts params
    @user = User.new(:invitation_token => params[:invitation_token])
    @user.email = @user.invitation.recipient_email if @user.invitation
    @button = 'Register'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @button = 'Update Profile'
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    puts params[:user]
    respond_to do |format|
      if @user.save
        format.html { redirect_to :users, notice: 'Registration successful.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User profile successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.hidden_field :invitation_token
    = f.label :username
    = f.text_field :username
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit @button

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

-# = link_to 'Show', @user
-# \|
-# = link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Network

%h2 Network
- @friendships.each do |friendship|
  = friendship.friend.username 
  = button_to "Remove friend", friendship, :method => :delete

%h2 Send invites to friends to join network
= link_to "Add more friends", new_invitation_path

%h2 Invitations Sent
- @invitations_sent.each do |invite|
  = invite.recipient_email
  = ['Unregistered', 'Not Accepted', 'Declined', 'Accepted'][invite.status]
  %br

%h2 Invitations Received
- @invitations_recv.each do |invite|
  = User.find(invite.sender_id).username
  = ['Unregistered', 'Not Accepted', 'Declined', 'Accepted'][invite.status]
  = button_to 'Accept Invite', friendships_path(:friend_id => invite.sender_id)
  %br

%h2 All users in the system - will be removed
  
- @users.each do |user|
  = user.username
  = button_to 'Add Friend', friendships_path(:friend_id => user)


-# %p
-#  = @invitations = current_user.sent_invitations.collect(&:recipient_email)

app/views/users/new.html.haml
%h1 New user registration

= render 'form'

-# = link_to 'Back', users_path

app/views/users/show.html.haml
%h1 Functionality coming soon. Stay tuned!

-# = link_to 'Edit', edit_user_path(@user)
-# \|
-# = link_to 'Back', users_path