config/routes.rb
Icoddle::Application.routes.draw do
  # landing page related
  root :to => 'leads#new', :as => :homepage
  match '/landing' => 'leads#new'

  # login/register/signup related
  match '/signup/:invitation_token' => 'users#new', :as => :signup
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  # artifacts of cruft
  get "home/index"
  match '/home' => 'home#index'
  match '/users' => 'users#index'

  # actual default REST route management
  # try rake routes to checkout all the helpers created for routes

  # stand alone routing
  resources :leads
  resources :user_sessions

  # nested routing
  resources :users
  resources :pets

  # not stand-alone but not sure if nesting helps 
  resources :invitations
  resources :friendships
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  validates_presence_of :email
  validates_format_of :email, :with => %r{.+@.+\..+}, :allow_blank => true
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

  skip_before_filter :require_login

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads }
    end
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
    @lead = Lead.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/new
  # GET /leads/new.json
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
    @lead = Lead.find(params[:id])
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(params[:lead])

    respond_to do |format|
      if @lead.save
        flash[:notice] = 'Thank you for your interest.'
        format.html { render action: 'edit' }
        format.json { render json: @lead, status: :created, location: @lead }
      else
        format.html { render action: "new" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leads/1
  # PUT /leads/1.json
  def update
    @lead = Lead.find(params[:id])

    respond_to do |format|
      if @lead.update_attributes(params[:lead])
        format.html { render action: 'edit', notice: 'Your email has been updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy

    respond_to do |format|
      format.html { redirect_to leads_url }
      format.json { head :ok }
    end
  end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_form.html.haml
%p Would you be interested in trying our free beta Online Pet Care Network starting in October?

%p If so, please provide an email where we can contact you.

= form_for @lead do |f|
  -if @lead.errors.any?
    #error_explanation
      %h2= "#{pluralize(@lead.errors.count, "error")} prohibited your email from being saved:"
      %ul
        - @lead.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Submit'

app/views/leads/_landing.html.haml
-content_for :style_overrides do
  \#header-links {display: none}
  \#header-login {display: none}
  \#tabs {display: none}

  \#landing-page {margin: 15px;}
  \#youtube-video {float: right; margin: 15px; margin-right: 0;}
  \.block {margin-top: 20px; margin-bottom: 20px;}
  \.highlight {font-style: italic; font-weight: bold;}

-content_for :youtube_video_DISABLED do
  \<iframe width="420" height="345" src="http://www.youtube.com/embed/n53c9ZZyTkw" frameborder="0" allowfullscreen></iframe>

-content_for :landing_pitch do
  %h1 Welcome to iCoddle.com
  .block
    %p 
      %span.highlight Take charge of your pet care
    %ul
      %li
        %p 
          %span.highlight Discover 
          pet owners in your neighborhood
      %li
        %p
          Bring 
          %span.highlight together
          friends and family
      %li
        %p
          %span.highlight Create
          your own, online, 
          %span.highlight secure
          pet care network
      %li
        %p
          %span.highlight Share
          and exchange your pet care needs

    %p
      %span.highlight www.iCoddle.com

#landing-page.row
  .column.grid_1
    &nbsp;
  #landing-pitch.column.grid_10
    #youtube-video
      =yield :youtube_video
    =yield :landing_pitch
  .column.grid_1
    &nbsp;
  #landing-form.row
    .column.grid_1
      &nbsp;
    .column.grid_10
      =yield :landing_form
    .column.grid_1
      &nbsp;

app/views/leads/edit.html.haml
-content_for :landing_form do
  = render 'form'

=render 'landing'

app/views/leads/index.html.haml
%h1 Listing leads

%table
  %tr
    %th Email
    %th
    %th
    %th

  - @leads.each do |lead|
    %tr
      %td= lead.email
      %td= link_to 'Show', lead
      %td= link_to 'Edit', edit_lead_path(lead)
      %td= link_to 'Destroy', lead, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Lead', new_lead_path

app/views/leads/new.html.haml
-content_for :landing_form do
  = render 'form'

=render 'landing'

app/views/leads/show.html.haml
%p
  %b Email:
  = @lead.email

= link_to 'Edit', edit_lead_path(@lead)
\|
= link_to 'Back', leads_path