config/routes.rb
Icoddle::Application.routes.draw do
  # landing page related
  root :to => 'leads#new', :as => :homepage
  match '/landing' => 'leads#new'

  # login/register/signup related
  match '/signup/:invitation_token' => 'users#new', :as => :signup
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  # artifacts of cruft
  get "home/index"
  match '/home' => 'home#index'
  match '/users' => 'users#index'

  # actual default REST route management
  # try rake routes to checkout all the helpers created for routes

  # stand alone routing
  resources :leads
  resources :user_sessions

  # nested routing
  resources :users
  resources :pets

  # not stand-alone but not sure if nesting helps 
  resources :invitations
  resources :friendships
end

app/views/layouts/_debug_context.html.haml
-content_for :debug_context do
  #debug_context
    %h1 Context Dump:
    %p
      Controller:
      = params[:controller]
    %p
      Action:
      = params[:action]
    %h2 params
    = debug(params)
    %h2 session:
    = debug(session)

    %h2 request
    = debug(request)
    %h2 response:
    = debug(response)

    %h2 action_name
    = debug(action_name)
    %h2 cookies
    = debug(cookies)
    %h2 headers
    = debug(headers)

=yield :debug_context_DISABLED

app/views/layouts/_flash_messages.html.haml
- if not flash.empty?
  #flash
    - if flash[:alert]
      #alert
        = flash[:alert]
    - if flash[:error]
      #error
        = flash[:error]
    - if flash[:warning]
      #warning
        = flash[:warning]
    - if flash[:notice]
      #notice
        = flash[:notice]
    - if flash[:message]
      #message
        = flash[:message]
    - if flash[:trace]
      #trace
        = flash[:trace]

app/views/layouts/_ga.html.haml
%script{ :type => "text/javascript"}
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26002744-1']);
  _gaq.push(['_trackPageview']);
  (function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') +
  '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/application.html.haml
!!! XML
!!!
%html
  %head
    %title Welcome to iCoddle
    = stylesheet_link_tag "layout"
    = yield :stylesheets
    %style{:type => 'text/css'}
      = yield :style_overrides

  %body
    = render :partial => 'layouts/ga' if Rails.env == 'production'

    #container
      #header.row
        #header-title.column.grid_6
          %a{:href => ""} iCoddle
        #header-links.column.grid_3
          %ul.header-ul
            %li
              %a{:href => ""} Products
            %li
              %a{:href => ""} About Us
        #header-login.column.grid_3
          -# %a{:href => ""} Login
          - if current_user
            %ul.header-ul
              %li
                = link_to "Edit Profile", edit_user_path(current_user.id)
              %li
                = link_to "Logout", :logout
          - else
            %ul.header-ul
              %li
                = link_to "Register", new_user_path
              %li
                = link_to "Login", :login
      #main
        .indentmenu#tabs
          %ul#tab-ul
            %li
              %a{:href => "/users"} Network
            %li
              %a{:href => "/pets"} Pets
            %li
              %a{:href => ""} Vacation
            %li
              %a{:href => ""} Feeder
        = render 'layouts/flash_messages'
        #content
          = yield
      #footer
        Copyright iCoddle, Inc. 2011
      =render 'layouts/debug_context'